spring.application.name=eeg-backend-crt
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.data.mongodb.uri=mongodb://localhost:27017/eegdb
spring.data.mongodb.database=eegdb
logging.level.org.springframework.data.mongodb=DEBUG
jwt.secret=mysupersecurelongsecretkey1234567890!@#$%^&*
server.port=8081 


